services:
  CyberSpectrum\ApiPlatformToolkit\EventListener\OverrideJwtTtlListener:
    arguments: [ '@request_stack', '%csap_toolkit.lexik_jwt_default_ttl%' ]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

  CyberSpectrum\ApiPlatformToolkit\EventListener\AddAudToJwtListener:
    arguments: [ '@request_stack' ]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

  CyberSpectrum\ApiPlatformToolkit\Serializer\Normalizer\AddApiLoginNormalizer:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 100
    arguments:
      - '@CyberSpectrum\ApiPlatformToolkit\Serializer\Normalizer\AddApiLoginNormalizer.inner'
      - '%api_platform.formats%'
      - login_url: '%csap_toolkit.lexik_jwt_login_url%'
        default_ttl: '%csap_toolkit.lexik_jwt_default_ttl%'
    public: false
