name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            output: '-o github-action -o default'
            composer_install: 'install --prefer-dist --no-interaction --no-scripts'
            phpcq_install: 'install'
          - php: 7.4
            output: '-o github-action -o default'
            composer_install: 'update --prefer-dist --no-interaction --no-scripts'
            phpcq_install: 'install'
          - php: 8.0
            output: '-o github-action -o default'
            composer_install: 'update --prefer-dist --no-interaction --no-scripts'
            phpcq_install: 'update'

    steps:
      - name: PHP ${{ matrix.php }} Pull source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/shivammathur/setup-php
      - name: PHP ${{ matrix.php }} Setup PHP.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: PHP ${{ matrix.php }} Cache composer cache directory
        uses: actions/cache@v1
        env:
          cache-name: composer-cache-dir-${{ matrix.php }}
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: PHP ${{ matrix.php }} Cache vendor directory
        uses: actions/cache@v1
        env:
          cache-name: composer-vendor-${{ matrix.php }}
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: PHP ${{ matrix.php }} Install composer dependencies
        run: composer ${{ matrix.composer_install }}

      - name: PHP ${{ matrix.php }} Update phpcq
        run: ./vendor/bin/phpcq self-update

      - name: PHP ${{ matrix.php }} Install phpcq toolchain
        run: ./vendor/bin/phpcq ${{ matrix.phpcq_install }} -v

      - name: PHP ${{ matrix.php }} Run tests
        run: ./vendor/bin/phpcq run ${{ matrix.output }} -v

      - name: PHP ${{ matrix.php }} Upload build directory to artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: phpcq-builds-php-${{ matrix.php }}
          path: .phpcq/build/
